Refactor many things
devs-immortal/The-Aether pull request #446
Opened 2021-08-02 12:00 UTC by SollyW

I'll pr this to make the changes visible. They are not yet complete.

2021-08-02 12:20 UTC, SollyW commented
Tf are you on about ci

2021-08-02 15:57 UTC, CDAGaming commented
```
/home/runner/work/The-Aether/The-Aether/src/main/java/com/aether/items/tools/SkyrootBucketItem.java:179: error: cannot find symbol
                    this.CPAonFluidPlaced(worldIn, posIn); //trigger CPA to attempt a portal light.
                        ^
  symbol: method CPAonFluidPlaced(World,BlockPos)
  ```
  onFluidPlaced would be the correct term here afaik, as I dont know anyone who would break camelCase standards.

2021-08-02 15:58 UTC, CDAGaming commented
Also if you wanted to, you could do your accessWidener reduction changes in here, as you mentioned awhile back that most could be replaced.

2021-08-03 11:35 UTC, SollyW commented
> ```
> /home/runner/work/The-Aether/The-Aether/src/main/java/com/aether/items/tools/SkyrootBucketItem.java:179: error: cannot find symbol
>                     this.CPAonFluidPlaced(worldIn, posIn); //trigger CPA to attempt a portal light.
>                         ^
>   symbol: method CPAonFluidPlaced(World,BlockPos)
> ```
> 
> onFluidPlaced would be the correct term here afaik, as I dont know anyone who would break camelCase standards.

I didn't write it; I'm not sure what's wrong there

2021-08-09 12:57 UTC, CDAGaming commented
@SollyW Rebase on newer changes to patch CI issues, mainly so we can have this have a workable CI build to compare with.

2021-08-09 18:59 UTC, Jack-Papel commented
Not sure if you saw the discord message, but we also agreed upon registering block items in the items class.

2021-08-12 21:00 UTC, Jack-Papel requested changes
Food bowls no longer update their texture when food is put in them.
They also sometimes can't be placed

2021-08-12 21:00 UTC, Jack-Papel commented on src/main/java/com/aether/mixin/entity/BoatEntityMixin.java
> +        else if (type == GOLDEN_OAK) cir.setReturnValue(AetherItems.GOLDEN_OAK_BOAT);
Why is Golden Oak imported unlike the others?

2021-08-12 21:00 UTC, Jack-Papel commented on src/main/java/com/aether/blocks/AetherBlocks.java
> +    private static final Action<Block> translucenRenderLayer = onClient((id, block) -> RenderLayers.BLOCKS.put(block, RenderLayer.getTranslucent()));
`translucen` -> `translucent`

2021-08-12 21:00 UTC, Jack-Papel commented on src/main/java/com/aether/entities/block/FloatingBlockEntity.java
> +
?

2021-08-14 03:00 UTC, SollyW commented
I can't reproduce an inability to place the food bowls, but the rendering has been fixed

2021-08-14 06:41 UTC, Jack-Papel approved these changes
Looks good to me 👍🏻

2021-08-15 04:01 UTC, Dragonoidzero approved these changes
![bless_2](https://user-images.githubusercontent.com/20349662/129466661-ccbb6588-0558-4321-94e7-2c88a2e70418.png)

2021-08-15 16:23 UTC, merged